import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import 'easymde/dist/easymde.min.css';
import ClientSessionProvider from '@/components/ClientSessionProvider';
import { auth } from '@/auth';

const workSans = localFont({
    src: [
        { path: './fonts/WorkSans-Black.ttf', weight: '900', style: 'normal' },
        { path: './fonts/WorkSans-ExtraBold.ttf', weight: '800', style: 'normal' },
        { path: './fonts/WorkSans-Bold.ttf', weight: '700', style: 'normal' },
        { path: './fonts/WorkSans-SemiBold.ttf', weight: '600', style: 'normal' },
        { path: './fonts/WorkSans-Medium.ttf', weight: '500', style: 'normal' },
        { path: './fonts/WorkSans-Regular.ttf', weight: '400', style: 'normal' },
        { path: './fonts/WorkSans-Thin.ttf', weight: '200', style: 'normal' },
        { path: './fonts/WorkSans-ExtraLight.ttf', weight: '100', style: 'normal' },
    ],
    variable: '--font-work-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    return (
        <html lang="en">
            <body className={workSans.variable}>
                <ClientSessionProvider session={session}>{children}</ClientSessionProvider>
            </body>
        </html>
    );
}
